_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
                - 75
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.3
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
dialect:
    value: postgresql
evaluated_at:
    value: 2026-03-17T01:12:35.486243
mode:
    value: mock
model:
    value: seeklhy/OmniSQL-7B
test_path:
    value: data/synthetic/pg_test.jsonl
test_size:
    value: 10
