// Auto-generated by scripts/build_demo_data.py
// Sources:
//   data/eval_omnisql-pg-v2-beam4_20260512_123345.jsonl
//   data/eval_omnisql-baseline-beam4_20260512_142518.jsonl
// DO NOT EDIT BY HAND — regenerate via `python scripts/build_demo_data.py`

export type SchemaName =
  | "ecommerce"
  | "fintech"
  | "healthcare"
  | "hr_system"
  | "saas_analytics";

export type Complexity = "simple" | "moderate" | "complex" | "highly_complex";

export interface DemoExample {
  id: string;
  schema: SchemaName;
  complexity: Complexity;
  question: string;
  generatedSql: string;
  referenceSql: string;
  bleu: number;
  execMatch: boolean;
  latencyMs: number;
  rows: Record<string, unknown>[];
}

export interface SchemaMeta {
  label: string;
  icon: string;
  color: string;
}

export interface BreakdownStat {
  executionAccuracy: number;
  validityRate: number;
}

export const SCHEMAS: Record<SchemaName, SchemaMeta> = {
  ecommerce: { label: "E-commerce", icon: "ShoppingBag", color: "#6ea8ff" },
  fintech: { label: "FinTech", icon: "Banknote", color: "#4ade80" },
  healthcare: { label: "Healthcare", icon: "Stethoscope", color: "#fb7185" },
  hr_system: { label: "HR System", icon: "Users", color: "#fbbf24" },
  saas_analytics: { label: "SaaS", icon: "BarChart3", color: "#c084ff" },
};

export const COMPLEXITY_LABELS: Record<Complexity, string> = {
  "simple": "Simple",
  "moderate": "Moderate",
  "complex": "Complex",
  "highly_complex": "Highly complex",
};

export const DEMO_EXAMPLES: DemoExample[] = [
  {
    id: "demo-01",
    schema: "saas_analytics",
    complexity: "highly_complex",
    question: "Can you show me the top 5 organizations with the most page views in the last quarter, along with the number of users in each organization and the date when each organization started its subscription?",
    generatedSql: `WITH page_views AS (SELECT org_id, COUNT(*) AS page_view_count FROM saas.events WHERE event_name = 'page_view' AND occurred_at > NOW() - INTERVAL '3 month' GROUP BY org_id) SELECT o.name, pv.page_view_count, u.user_count, s.started_at FROM saas.organizations o JOIN page_views pv ON o.id = pv.org_id JOIN (SELECT org_id, COUNT(*) AS user_count FROM saas.users GROUP BY org_id) u ON o.id = u.org_id JOIN saas.subscriptions s ON o.id = s.org_id ORDER BY pv.page_view_count DESC LIMIT 5;`,
    referenceSql: `WITH page_views AS (SELECT org_id, COUNT(*) OVER (PARTITION BY org_id) AS page_view_count FROM saas.events WHERE event_name = 'page_view' AND occurred_at > NOW() - INTERVAL '3 month'), subs AS (SELECT org_id, started_at, ROW_NUMBER() OVER (PARTITION BY org_id ORDER BY started_at) AS sub_num FROM saas.subscriptions) SELECT o.name, pv.page_view_count, u.user_count, s.started_at FROM saas.organizations o JOIN page_views pv ON o.id = pv.org_id JOIN (SELECT org_id, COUNT(*) AS user_count FROM saas.users GROUP BY org_id) u ON o.id = u.org_id JOIN subs s ON o.id = s.org_id WHERE s.sub_num = 1 ORDER BY pv.page_view_count DESC LIMIT 5;`,
    bleu: 0.6951,
    execMatch: true,
    latencyMs: 1200,
    rows: [{"name": "pro", "count": 14}, {"name": "free", "count": 21}, {"name": "enterprise", "count": 28}, {"name": "team", "count": 35}],
  },
  {
    id: "demo-02",
    schema: "fintech",
    complexity: "moderate",
    question: "List all accounts that have a balance greater than $1000 and are of type 'checking' or 'savings'.",
    generatedSql: `SELECT * FROM fintech.accounts WHERE balance > 1000 AND account_type IN ('checking', 'savings');`,
    referenceSql: `SELECT * FROM fintech.accounts WHERE balance > 1000 AND account_type IN ('checking', 'savings');`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1337,
    rows: [{"id": 1, "account_type": "checking", "amount": 695.0, "category": "food"}, {"id": 2, "account_type": "savings", "amount": 1042.5, "category": "transport"}, {"id": 3, "account_type": "checking", "amount": 1390.0, "category": "food"}, {"id": 4, "account_type": "credit", "amount": 1737.5, "category": "entertainment"}],
  },
  {
    id: "demo-03",
    schema: "hr_system",
    complexity: "complex",
    question: "Find the top 2 employees with the highest total salary in each department, considering only departments with more than 5 employees.",
    generatedSql: `WITH ranked_salaries AS (SELECT e.department_id, e.name, e.salary, ROW_NUMBER() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) AS rank FROM hr.employees e JOIN hr.departments d ON e.department_id = d.id WHERE d.id IN (SELECT department_id FROM hr.employees GROUP BY department_id HAVING COUNT(*) > 5)) SELECT department_id, name, salary FROM ranked_salaries WHERE rank <= 2;`,
    referenceSql: `WITH ranked_employees AS (SELECT e.department_id, e.name, e.title, e.salary, DENSE_RANK() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) AS rank FROM hr.employees e JOIN hr.departments d ON e.department_id = d.id WHERE d.id IN (SELECT department_id FROM hr.employees GROUP BY department_id HAVING COUNT(*) > 5)) SELECT department_id, name, title, salary FROM ranked_employees WHERE rank <= 2;`,
    bleu: 0.8565,
    execMatch: true,
    latencyMs: 1474,
    rows: [{"name": "Engineering", "count": 14}, {"name": "Sales", "count": 21}, {"name": "Marketing", "count": 28}, {"name": "HR", "count": 35}],
  },
  {
    id: "demo-04",
    schema: "fintech",
    complexity: "simple",
    question: "Get all transactions that occurred in the year 2022",
    generatedSql: `SELECT * FROM fintech.transactions WHERE EXTRACT(YEAR FROM occurred_at) = 2022;`,
    referenceSql: `SELECT * FROM fintech.transactions WHERE EXTRACT(YEAR FROM occurred_at) = 2022;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1611,
    rows: [{"id": 1, "account_type": "checking", "amount": 695.0, "category": "food"}, {"id": 2, "account_type": "savings", "amount": 1042.5, "category": "transport"}, {"id": 3, "account_type": "checking", "amount": 1390.0, "category": "food"}, {"id": 4, "account_type": "credit", "amount": 1737.5, "category": "entertainment"}],
  },
  {
    id: "demo-05",
    schema: "healthcare",
    complexity: "moderate",
    question: "Find the number of patients who have been diagnosed with a condition in the last 6 months.",
    generatedSql: `SELECT COUNT(DISTINCT p.id) FROM healthcare.patients p JOIN healthcare.diagnoses d ON p.id = d.patient_id WHERE d.diagnosed_at > NOW() - INTERVAL '6 months';`,
    referenceSql: `SELECT COUNT(DISTINCT p.id) FROM healthcare.patients p JOIN healthcare.diagnoses d ON p.id = d.patient_id WHERE d.diagnosed_at > NOW() - INTERVAL '6 months';`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1748,
    rows: [{"value": "result_1"}, {"value": "result_2"}, {"value": "result_3"}],
  },
  {
    id: "demo-06",
    schema: "hr_system",
    complexity: "moderate",
    question: "What is the distribution of time off request status?",
    generatedSql: `SELECT status, COUNT(*) AS count FROM hr.time_off_requests GROUP BY status;`,
    referenceSql: `SELECT status, COUNT(*) as count FROM hr.time_off_requests GROUP BY status;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1885,
    rows: [{"name": "Engineering", "count": 14}, {"name": "Sales", "count": 21}, {"name": "Marketing", "count": 28}, {"name": "HR", "count": 35}],
  },
  {
    id: "demo-07",
    schema: "hr_system",
    complexity: "highly_complex",
    question: "What are the titles of employees who have given performance reviews in the 'Q3 2024' review period, and what are the average ratings given by these employees?",
    generatedSql: `SELECT e.title, AVG(pr.rating) AS average_rating FROM hr.employees e JOIN hr.performance_reviews pr ON e.id = pr.reviewer_id WHERE pr.review_period = 'Q3 2024' GROUP BY e.title;`,
    referenceSql: `SELECT he.title, AVG(pr.rating) AS avg_rating FROM hr.performance_reviews pr JOIN hr.employees he ON pr.reviewer_id = he.id WHERE pr.review_period = 'Q3 2024' GROUP BY he.title;`,
    bleu: 0.5928,
    execMatch: true,
    latencyMs: 1222,
    rows: [{"name": "Engineering", "avg": 1247.5}, {"name": "Sales", "avg": 1679.6}, {"name": "Marketing", "avg": 2111.7}, {"name": "HR", "avg": 2543.8}],
  },
  {
    id: "demo-08",
    schema: "saas_analytics",
    complexity: "complex",
    question: "Find the average monthly recurring revenue for each plan, excluding the 'free' plan",
    generatedSql: `SELECT plan, AVG(mrr) AS avg_mrr FROM saas.subscriptions WHERE plan != 'free' GROUP BY plan;`,
    referenceSql: `SELECT plan, AVG(mrr) AS avg_mrr FROM saas.subscriptions WHERE plan != 'free' GROUP BY plan;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1359,
    rows: [{"name": "pro", "avg": 1247.5}, {"name": "free", "avg": 1679.6}, {"name": "enterprise", "avg": 2111.7}, {"name": "team", "avg": 2543.8}],
  },
  {
    id: "demo-09",
    schema: "fintech",
    complexity: "complex",
    question: "Can you provide the loan ID and principal for the loan with the highest interest rate that is currently active?",
    generatedSql: `SELECT id, principal FROM fintech.loans WHERE status = 'active' ORDER BY interest_rate DESC LIMIT 1;`,
    referenceSql: `SELECT id, principal FROM fintech.loans WHERE status = 'active' ORDER BY interest_rate DESC LIMIT 1;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1496,
    rows: [{"id": 1, "name": "Alice Chen", "score": 95.3}, {"id": 2, "name": "Bob Williams", "score": 91.1}, {"id": 3, "name": "Carol Singh", "score": 86.9}, {"id": 4, "name": "Dave Park", "score": 82.7}, {"id": 5, "name": "Eve Martinez", "score": 78.5}],
  },
  {
    id: "demo-10",
    schema: "hr_system",
    complexity: "simple",
    question: "List all unique job titles in the company",
    generatedSql: `SELECT DISTINCT title FROM hr.employees;`,
    referenceSql: `SELECT DISTINCT title FROM hr.employees;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1633,
    rows: [{"title": "Engineer"}, {"title": "Senior Engineer"}, {"title": "Manager"}, {"title": "Director"}, {"title": "Analyst"}],
  },
  {
    id: "demo-11",
    schema: "saas_analytics",
    complexity: "moderate",
    question: "What are the top 5 organizations with the most active users, based on the number of page views in the last 30 days?",
    generatedSql: `SELECT o.name, COUNT(DISTINCT u.id) AS active_users FROM saas.organizations o JOIN saas.users u ON o.id = u.org_id JOIN saas.events e ON u.id = e.user_id WHERE e.event_name = 'page_view' AND e.occurred_at > NOW() - INTERVAL '30 days' GROUP BY o.name ORDER BY active_users DESC LIMIT 5;`,
    referenceSql: `SELECT o.name, COUNT(e.id) AS page_views FROM saas.organizations o JOIN saas.users u ON o.id = u.org_id JOIN saas.events e ON u.id = e.user_id WHERE e.event_name = 'page_view' AND e.occurred_at > NOW() - INTERVAL '30 days' GROUP BY o.id, o.name ORDER BY page_views DESC LIMIT 5;`,
    bleu: 0.8501,
    execMatch: true,
    latencyMs: 1770,
    rows: [{"name": "pro", "count": 14}, {"name": "free", "count": 21}, {"name": "enterprise", "count": 28}, {"name": "team", "count": 35}],
  },
  {
    id: "demo-12",
    schema: "healthcare",
    complexity: "complex",
    question: "What is the number of completed appointments for each provider, sorted by provider name in descending order?",
    generatedSql: `SELECT p.name, COUNT(a.id) AS completed_appointments FROM healthcare.providers p JOIN healthcare.appointments a ON p.id = a.provider_id WHERE a.status = 'completed' GROUP BY p.name ORDER BY p.name DESC;`,
    referenceSql: `SELECT p.name, COUNT(a.id) AS completed_appointments FROM healthcare.providers p JOIN healthcare.appointments a ON p.id = a.provider_id WHERE a.status = 'completed' GROUP BY p.name ORDER BY p.name DESC;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1907,
    rows: [{"name": "cardiology", "count": 14}, {"name": "neurology", "count": 21}, {"name": "pediatrics", "count": 28}, {"name": "general", "count": 35}],
  },
  {
    id: "demo-13",
    schema: "ecommerce",
    complexity: "moderate",
    question: "What are the names of products that have been ordered by at least two different users?",
    generatedSql: `SELECT p.name FROM products p JOIN order_items oi ON p.id = oi.product_id JOIN orders o ON oi.order_id = o.id GROUP BY p.name HAVING COUNT(DISTINCT o.user_id) >= 2;`,
    referenceSql: `SELECT DISTINCT p.name FROM products p JOIN order_items oi ON p.id = oi.product_id JOIN orders o ON oi.order_id = o.id GROUP BY p.name HAVING COUNT(DISTINCT o.user_id) >= 2;`,
    bleu: 0.9609,
    execMatch: true,
    latencyMs: 1244,
    rows: [{"name": "electronics", "count": 14}, {"name": "clothing", "count": 21}, {"name": "books", "count": 28}, {"name": "home", "count": 35}],
  },
  {
    id: "demo-14",
    schema: "healthcare",
    complexity: "highly_complex",
    question: "List all providers who have scheduled appointments with patients who are 65 years or older, along with the scheduled date and time, and the appointment type, using a CTE to first calculate the age of the patients.",
    generatedSql: `WITH patient_age AS (SELECT id, name, date_of_birth, EXTRACT(YEAR FROM AGE(CURRENT_DATE, date_of_birth)) AS age FROM healthcare.patients) SELECT p.name AS provider_name, a.scheduled_at, a.appointment_type FROM healthcare.providers p JOIN healthcare.appointments a ON p.id = a.provider_id JOIN patient_age pa ON a.patient_id = pa.id WHERE pa.age >= 65;`,
    referenceSql: `WITH patient_age AS (SELECT id, EXTRACT(YEAR FROM AGE(CURRENT_DATE, date_of_birth)) AS age FROM healthcare.patients) SELECT p.name, a.scheduled_at, a.appointment_type FROM healthcare.providers p JOIN healthcare.appointments a ON p.id = a.provider_id JOIN patient_age pa ON a.patient_id = pa.id WHERE pa.age >= 65;`,
    bleu: 0.8959,
    execMatch: true,
    latencyMs: 1381,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-15",
    schema: "ecommerce",
    complexity: "complex",
    question: "What are the names of users who placed an order in the last month, along with the total amount they spent, ordered by the total amount in descending order?",
    generatedSql: `SELECT u.name, SUM(o.total) AS total_spent FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at >= NOW() - INTERVAL '1 month' GROUP BY u.name ORDER BY total_spent DESC;`,
    referenceSql: `SELECT u.name, SUM(o.total) AS total_spent FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at > NOW() - INTERVAL '1 month' GROUP BY u.name ORDER BY total_spent DESC;`,
    bleu: 0.9487,
    execMatch: true,
    latencyMs: 1518,
    rows: [{"name": "electronics", "total": 12400}, {"name": "clothing", "total": 21150}, {"name": "books", "total": 29900}, {"name": "home", "total": 38650}],
  },
  {
    id: "demo-16",
    schema: "saas_analytics",
    complexity: "simple",
    question: "What are the distinct event names that have occurred in the last month?",
    generatedSql: `SELECT DISTINCT event_name FROM saas.events WHERE occurred_at > NOW() - INTERVAL '1 month';`,
    referenceSql: `SELECT DISTINCT event_name FROM saas.events WHERE occurred_at > NOW() - INTERVAL '1 month';`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1655,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-17",
    schema: "fintech",
    complexity: "highly_complex",
    question: "Find the top 5 transaction categories by average transaction amount, excluding credits and transfers.",
    generatedSql: `SELECT category, AVG(amount) AS avg_amount FROM fintech.transactions WHERE transaction_type NOT IN ('credit', 'transfer') GROUP BY category ORDER BY avg_amount DESC LIMIT 5;`,
    referenceSql: `SELECT category, AVG(amount) AS avg_amount FROM fintech.transactions WHERE transaction_type NOT IN ('credit', 'transfer') GROUP BY category ORDER BY avg_amount DESC LIMIT 5;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1792,
    rows: [{"name": "checking", "avg": 1247.5}, {"name": "savings", "avg": 1679.6}, {"name": "credit", "avg": 2111.7}, {"name": "investment", "avg": 2543.8}],
  },
  {
    id: "demo-18",
    schema: "healthcare",
    complexity: "simple",
    question: "What is the most common appointment type?",
    generatedSql: `SELECT appointment_type, COUNT(*) AS count FROM healthcare.appointments GROUP BY appointment_type ORDER BY count DESC LIMIT 1;`,
    referenceSql: `SELECT appointment_type, COUNT(*) AS count FROM healthcare.appointments GROUP BY appointment_type ORDER BY count DESC LIMIT 1;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1929,
    rows: [{"name": "cardiology", "count": 14}, {"name": "neurology", "count": 21}, {"name": "pediatrics", "count": 28}, {"name": "general", "count": 35}],
  },
  {
    id: "demo-19",
    schema: "ecommerce",
    complexity: "simple",
    question: "What are the names of users who have placed an order in the last week?",
    generatedSql: `SELECT DISTINCT u.name FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at > NOW() - INTERVAL '1 week';`,
    referenceSql: `SELECT DISTINCT u.name FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at > NOW() - INTERVAL '1 week';`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1266,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-20",
    schema: "ecommerce",
    complexity: "highly_complex",
    question: "Find the average order value for each tier of users, considering only orders with a 'delivered' status, and include the tier name",
    generatedSql: `SELECT u.tier, AVG(o.total) AS average_order_value FROM users u JOIN orders o ON u.id = o.user_id WHERE o.status = 'delivered' GROUP BY u.tier;`,
    referenceSql: `SELECT u.tier, AVG(o.total) AS avg_order_value FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'delivered' GROUP BY u.tier;`,
    bleu: 0.689,
    execMatch: true,
    latencyMs: 1403,
    rows: [{"name": "electronics", "avg": 1247.5}, {"name": "clothing", "avg": 1679.6}, {"name": "books", "avg": 2111.7}, {"name": "home", "avg": 2543.8}],
  },
];

// Aggregated metrics from real eval runs (200-pair test set each)
export const EVAL_METRICS = {
  testSize: 200,
  finetuned: {
    overall: {
      executionAccuracy: 0.6600,
      validityRate:      0.9600,
      bleu:              0.6048,
    },
    bySchema: {
      "hr_system": { executionAccuracy: 0.5854, validityRate: 0.9756 },
      "ecommerce": { executionAccuracy: 0.4500, validityRate: 1.0000 },
      "fintech": { executionAccuracy: 0.7692, validityRate: 0.9744 },
      "healthcare": { executionAccuracy: 0.7750, validityRate: 0.9250 },
      "saas_analytics": { executionAccuracy: 0.7250, validityRate: 0.9250 }
    } as Record<SchemaName, BreakdownStat>,
    byComplexity: {
      "complex": { executionAccuracy: 0.5370, validityRate: 0.9259 },
      "moderate": { executionAccuracy: 0.7000, validityRate: 0.9857 },
      "highly_complex": { executionAccuracy: 0.4286, validityRate: 0.9143 },
      "simple": { executionAccuracy: 0.9512, validityRate: 1.0000 }
    } as Record<Complexity, BreakdownStat>,
  },
  baseline: {
    overall: {
      executionAccuracy: 0.2300,
      validityRate:      0.3550,
      bleu:              0.3258,
    },
    bySchema: {
      "hr_system": { executionAccuracy: 0.2927, validityRate: 0.4634 },
      "ecommerce": { executionAccuracy: 0.3000, validityRate: 0.6500 },
      "fintech": { executionAccuracy: 0.2821, validityRate: 0.3590 },
      "healthcare": { executionAccuracy: 0.0750, validityRate: 0.0750 },
      "saas_analytics": { executionAccuracy: 0.2000, validityRate: 0.2250 }
    } as Record<SchemaName, BreakdownStat>,
    byComplexity: {
      "complex": { executionAccuracy: 0.2222, validityRate: 0.3704 },
      "moderate": { executionAccuracy: 0.2571, validityRate: 0.3714 },
      "highly_complex": { executionAccuracy: 0.2000, validityRate: 0.4571 },
      "simple": { executionAccuracy: 0.2195, validityRate: 0.2195 }
    } as Record<Complexity, BreakdownStat>,
  },
} as const;
