// Auto-generated by scripts/build_demo_data.py
// Sources:
//   data/eval_omnisql-pg-finetuned-full_20260505_132926.jsonl
//   data/eval_omnisql-7b-baseline-full_20260505_145351.jsonl
// DO NOT EDIT BY HAND — regenerate via `python scripts/build_demo_data.py`

export type SchemaName =
  | "ecommerce"
  | "fintech"
  | "healthcare"
  | "hr_system"
  | "saas_analytics";

export type Complexity = "simple" | "moderate" | "complex" | "highly_complex";

export interface DemoExample {
  id: string;
  schema: SchemaName;
  complexity: Complexity;
  question: string;
  generatedSql: string;
  referenceSql: string;
  bleu: number;
  execMatch: boolean;
  latencyMs: number;
  rows: Record<string, unknown>[];
}

export interface SchemaMeta {
  label: string;
  icon: string;
  color: string;
}

export interface BreakdownStat {
  executionAccuracy: number;
  validityRate: number;
}

export const SCHEMAS: Record<SchemaName, SchemaMeta> = {
  ecommerce: { label: "E-commerce", icon: "ShoppingBag", color: "#6ea8ff" },
  fintech: { label: "FinTech", icon: "Banknote", color: "#4ade80" },
  healthcare: { label: "Healthcare", icon: "Stethoscope", color: "#fb7185" },
  hr_system: { label: "HR System", icon: "Users", color: "#fbbf24" },
  saas_analytics: { label: "SaaS", icon: "BarChart3", color: "#c084ff" },
};

export const COMPLEXITY_LABELS: Record<Complexity, string> = {
  "simple": "Simple",
  "moderate": "Moderate",
  "complex": "Complex",
  "highly_complex": "Highly complex",
};

export const DEMO_EXAMPLES: DemoExample[] = [
  {
    id: "demo-01",
    schema: "saas_analytics",
    complexity: "highly_complex",
    question: "Can you show me the top 5 organizations with the most page views in the last quarter, along with the number of users in each organization and the date when each organization started its subscription?",
    generatedSql: `WITH page_views AS (SELECT org_id, COUNT(*) AS num_page_views FROM saas.events WHERE event_name = 'page_view' AND occurred_at > NOW() - INTERVAL '3 months' GROUP BY org_id), org_info AS (SELECT o.id, o.name, p.num_page_views, u.num_users, s.started_at FROM saas.organizations o JOIN page_views p ON o.id = p.org_id LEFT JOIN (SELECT org_id, COUNT(DISTINCT user_id) AS num_users FROM saas.events GROUP BY org_id) u ON o.id = u.org_id LEFT JOIN saas.subscriptions s ON o.id = s.org_id) SELECT * FROM org_info ORDER BY num_page_views DESC LIMIT 5;`,
    referenceSql: `WITH page_views AS (SELECT org_id, COUNT(*) OVER (PARTITION BY org_id) AS page_view_count FROM saas.events WHERE event_name = 'page_view' AND occurred_at > NOW() - INTERVAL '3 month'), subs AS (SELECT org_id, started_at, ROW_NUMBER() OVER (PARTITION BY org_id ORDER BY started_at) AS sub_num FROM saas.subscriptions) SELECT o.name, pv.page_view_count, u.user_count, s.started_at FROM saas.organizations o JOIN page_views pv ON o.id = pv.org_id JOIN (SELECT org_id, COUNT(*) AS user_count FROM saas.users GROUP BY org_id) u ON o.id = u.org_id JOIN subs s ON o.id = s.org_id WHERE s.sub_num = 1 ORDER BY pv.page_view_count DESC LIMIT 5;`,
    bleu: 0.5224,
    execMatch: true,
    latencyMs: 1200,
    rows: [{"name": "pro", "count": 14}, {"name": "free", "count": 21}, {"name": "enterprise", "count": 28}, {"name": "team", "count": 35}],
  },
  {
    id: "demo-02",
    schema: "fintech",
    complexity: "moderate",
    question: "List all accounts that have a balance greater than $1000 and are of type 'checking' or 'savings'.",
    generatedSql: `SELECT * FROM fintech.accounts WHERE balance > 1000 AND account_type IN ('checking', 'savings');`,
    referenceSql: `SELECT * FROM fintech.accounts WHERE balance > 1000 AND account_type IN ('checking', 'savings');`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1337,
    rows: [{"id": 1, "account_type": "checking", "amount": 695.0, "category": "food"}, {"id": 2, "account_type": "savings", "amount": 1042.5, "category": "transport"}, {"id": 3, "account_type": "checking", "amount": 1390.0, "category": "food"}, {"id": 4, "account_type": "credit", "amount": 1737.5, "category": "entertainment"}],
  },
  {
    id: "demo-03",
    schema: "hr_system",
    complexity: "complex",
    question: "Get the names and titles of all employees who have a higher salary than the average salary of their department, and have been with the company for more than 2 years.",
    generatedSql: `SELECT e.name, e.title FROM hr.employees e JOIN (SELECT department_id, AVG(salary) AS avg_salary FROM hr.employees GROUP BY department_id) d ON e.department_id = d.department_id WHERE e.salary > d.avg_salary AND (CURRENT_DATE - e.hire_date) > INTERVAL '2 year';`,
    referenceSql: `WITH avg_salaries AS (SELECT department_id, AVG(salary) AS avg_salary FROM hr.employees GROUP BY department_id) SELECT e.name, e.title FROM hr.employees e JOIN avg_salaries a ON e.department_id = a.department_id WHERE e.salary > a.avg_salary AND AGE(CURRENT_DATE, e.hire_date) > INTERVAL '2 year';`,
    bleu: 0.7236,
    execMatch: false,
    latencyMs: 1474,
    rows: [{"name": "Engineering", "avg": 1247.5}, {"name": "Sales", "avg": 1679.6}, {"name": "Marketing", "avg": 2111.7}, {"name": "HR", "avg": 2543.8}],
  },
  {
    id: "demo-04",
    schema: "fintech",
    complexity: "simple",
    question: "Get all transactions that occurred in the year 2022",
    generatedSql: `SELECT * FROM fintech.transactions WHERE EXTRACT(YEAR FROM occurred_at) = 2022;`,
    referenceSql: `SELECT * FROM fintech.transactions WHERE EXTRACT(YEAR FROM occurred_at) = 2022;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1611,
    rows: [{"id": 1, "account_type": "checking", "amount": 695.0, "category": "food"}, {"id": 2, "account_type": "savings", "amount": 1042.5, "category": "transport"}, {"id": 3, "account_type": "checking", "amount": 1390.0, "category": "food"}, {"id": 4, "account_type": "credit", "amount": 1737.5, "category": "entertainment"}],
  },
  {
    id: "demo-05",
    schema: "healthcare",
    complexity: "moderate",
    question: "Get a list of patients who have missed their appointments (status is 'no_show') and have been diagnosed with a condition.",
    generatedSql: `SELECT p.name, d.description FROM healthcare.patients p JOIN healthcare.appointments a ON p.id = a.patient_id JOIN healthcare.diagnoses d ON a.id = d.appointment_id WHERE a.status = 'no_show';`,
    referenceSql: `SELECT p.name FROM healthcare.patients p JOIN healthcare.appointments a ON p.id = a.patient_id JOIN healthcare.diagnoses d ON p.id = d.patient_id WHERE a.status = 'no_show' AND d.icd_code IS NOT NULL;`,
    bleu: 0.7294,
    execMatch: true,
    latencyMs: 1748,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-06",
    schema: "hr_system",
    complexity: "moderate",
    question: "What is the distribution of time off request status?",
    generatedSql: `SELECT status, COUNT(*) AS count FROM hr.time_off_requests GROUP BY status;`,
    referenceSql: `SELECT status, COUNT(*) as count FROM hr.time_off_requests GROUP BY status;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1885,
    rows: [{"name": "Engineering", "count": 14}, {"name": "Sales", "count": 21}, {"name": "Marketing", "count": 28}, {"name": "HR", "count": 35}],
  },
  {
    id: "demo-07",
    schema: "hr_system",
    complexity: "highly_complex",
    question: "What are the titles of employees who have given performance reviews in the 'Q3 2024' review period, and what are the average ratings given by these employees?",
    generatedSql: `SELECT e.title, AVG(pr.rating) AS avg_rating FROM hr.employees e JOIN hr.performance_reviews pr ON e.id = pr.reviewer_id WHERE pr.review_period = 'Q3 2024' GROUP BY e.title;`,
    referenceSql: `SELECT he.title, AVG(pr.rating) AS avg_rating FROM hr.performance_reviews pr JOIN hr.employees he ON pr.reviewer_id = he.id WHERE pr.review_period = 'Q3 2024' GROUP BY he.title;`,
    bleu: 0.6609,
    execMatch: true,
    latencyMs: 1222,
    rows: [{"name": "Engineering", "avg": 1247.5}, {"name": "Sales", "avg": 1679.6}, {"name": "Marketing", "avg": 2111.7}, {"name": "HR", "avg": 2543.8}],
  },
  {
    id: "demo-08",
    schema: "saas_analytics",
    complexity: "complex",
    question: "Find the average monthly recurring revenue for each plan, excluding the 'free' plan",
    generatedSql: `SELECT plan, AVG(mrr) AS avg_mrr FROM saas.subscriptions WHERE plan != 'free' GROUP BY plan;`,
    referenceSql: `SELECT plan, AVG(mrr) AS avg_mrr FROM saas.subscriptions WHERE plan != 'free' GROUP BY plan;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1359,
    rows: [{"name": "pro", "avg": 1247.5}, {"name": "free", "avg": 1679.6}, {"name": "enterprise", "avg": 2111.7}, {"name": "team", "avg": 2543.8}],
  },
  {
    id: "demo-09",
    schema: "fintech",
    complexity: "complex",
    question: "Can you provide the loan ID and principal for the loan with the highest interest rate that is currently active?",
    generatedSql: `SELECT id, principal FROM fintech.loans WHERE status = 'active' ORDER BY interest_rate DESC LIMIT 1;`,
    referenceSql: `SELECT id, principal FROM fintech.loans WHERE status = 'active' ORDER BY interest_rate DESC LIMIT 1;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1496,
    rows: [{"id": 1, "name": "Alice Chen", "score": 95.3}, {"id": 2, "name": "Bob Williams", "score": 91.1}, {"id": 3, "name": "Carol Singh", "score": 86.9}, {"id": 4, "name": "Dave Park", "score": 82.7}, {"id": 5, "name": "Eve Martinez", "score": 78.5}],
  },
  {
    id: "demo-10",
    schema: "hr_system",
    complexity: "simple",
    question: "List all unique job titles in the company",
    generatedSql: `SELECT DISTINCT title FROM hr.employees;`,
    referenceSql: `SELECT DISTINCT title FROM hr.employees;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1633,
    rows: [{"title": "Engineer"}, {"title": "Senior Engineer"}, {"title": "Manager"}, {"title": "Director"}, {"title": "Analyst"}],
  },
  {
    id: "demo-11",
    schema: "saas_analytics",
    complexity: "moderate",
    question: "How many users are owners of an organization and have logged in in the last week?",
    generatedSql: `SELECT COUNT(DISTINCT u.id) FROM saas.users u JOIN saas.events e ON u.id = e.user_id WHERE u.role = 'owner' AND e.event_name = 'login' AND e.occurred_at > NOW() - INTERVAL '7 days';`,
    referenceSql: `SELECT COUNT(DISTINCT u.id) FROM saas.users u JOIN saas.events e ON u.id = e.user_id WHERE u.role = 'owner' AND e.event_name = 'login' AND e.occurred_at > NOW() - INTERVAL '1 week';`,
    bleu: 0.9494,
    execMatch: true,
    latencyMs: 1770,
    rows: [{"value": "result_1"}, {"value": "result_2"}, {"value": "result_3"}],
  },
  {
    id: "demo-12",
    schema: "healthcare",
    complexity: "complex",
    question: "Get the names of patients who have been diagnosed with a condition that has an ICD code that starts with 'E', along with the ICD code and description of the diagnosis.",
    generatedSql: `SELECT p.name, d.icd_code, d.description FROM healthcare.patients p JOIN healthcare.diagnoses d ON p.id = d.patient_id WHERE d.icd_code LIKE 'E%';`,
    referenceSql: `SELECT p.name, d.icd_code, d.description FROM healthcare.patients p JOIN healthcare.diagnoses d ON p.id = d.patient_id WHERE d.icd_code ILIKE 'E%';`,
    bleu: 0.9318,
    execMatch: true,
    latencyMs: 1907,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-13",
    schema: "ecommerce",
    complexity: "moderate",
    question: "Show me the top 5 products by total quantity sold, excluding products from the 'electronics' category.",
    generatedSql: `SELECT p.name, SUM(oi.quantity) AS total_quantity FROM order_items oi JOIN products p ON oi.product_id = p.id WHERE p.category != 'electronics' GROUP BY p.name ORDER BY total_quantity DESC LIMIT 5;`,
    referenceSql: `SELECT p.name, SUM(oi.quantity) AS total_quantity FROM order_items oi JOIN products p ON oi.product_id = p.id WHERE p.category != 'electronics' GROUP BY p.name ORDER BY total_quantity DESC LIMIT 5;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1244,
    rows: [{"name": "electronics", "total": 12400}, {"name": "clothing", "total": 21150}, {"name": "books", "total": 29900}, {"name": "home", "total": 38650}],
  },
  {
    id: "demo-14",
    schema: "healthcare",
    complexity: "highly_complex",
    question: "List all providers who have scheduled appointments with patients who are 65 years or older, along with the scheduled date and time, and the appointment type, using a CTE to first calculate the age of the patients.",
    generatedSql: `WITH patient_age AS (SELECT p.id, p.name, p.date_of_birth, EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.date_of_birth)) AS age FROM healthcare.patients p WHERE EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.date_of_birth)) >= 65) SELECT pr.name, a.scheduled_at, a.appointment_type FROM healthcare.appointments a JOIN patient_age pa ON a.patient_id = pa.id JOIN healthcare.providers pr ON a.provider_id = pr.id;`,
    referenceSql: `WITH patient_age AS (SELECT id, EXTRACT(YEAR FROM AGE(CURRENT_DATE, date_of_birth)) AS age FROM healthcare.patients) SELECT p.name, a.scheduled_at, a.appointment_type FROM healthcare.providers p JOIN healthcare.appointments a ON p.id = a.provider_id JOIN patient_age pa ON a.patient_id = pa.id WHERE pa.age >= 65;`,
    bleu: 0.5327,
    execMatch: true,
    latencyMs: 1381,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-15",
    schema: "ecommerce",
    complexity: "complex",
    question: "What are the names of users who placed an order in the last month, along with the total amount they spent, ordered by the total amount in descending order?",
    generatedSql: `SELECT u.name, SUM(o.total) AS total_spent FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at > NOW() - INTERVAL '1 month' GROUP BY u.name ORDER BY total_spent DESC;`,
    referenceSql: `SELECT u.name, SUM(o.total) AS total_spent FROM users u JOIN orders o ON u.id = o.user_id WHERE o.created_at > NOW() - INTERVAL '1 month' GROUP BY u.name ORDER BY total_spent DESC;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1518,
    rows: [{"name": "electronics", "total": 12400}, {"name": "clothing", "total": 21150}, {"name": "books", "total": 29900}, {"name": "home", "total": 38650}],
  },
  {
    id: "demo-16",
    schema: "saas_analytics",
    complexity: "simple",
    question: "List all the unique event names that occurred in the last 30 days",
    generatedSql: `SELECT DISTINCT event_name FROM saas.events WHERE occurred_at > NOW() - INTERVAL '30 day';`,
    referenceSql: `SELECT DISTINCT event_name FROM saas.events WHERE occurred_at > NOW() - INTERVAL '30 day';`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1655,
    rows: [{"name": "Alice Chen"}, {"name": "Bob Williams"}, {"name": "Carol Singh"}, {"name": "Dave Park"}, {"name": "Eve Martinez"}],
  },
  {
    id: "demo-17",
    schema: "fintech",
    complexity: "highly_complex",
    question: "Find the top 5 transaction categories by average transaction amount, excluding credits and transfers.",
    generatedSql: `SELECT category, AVG(amount) AS avg_amount FROM fintech.transactions WHERE transaction_type NOT IN ('credit', 'transfer') GROUP BY category ORDER BY avg_amount DESC LIMIT 5;`,
    referenceSql: `SELECT category, AVG(amount) AS avg_amount FROM fintech.transactions WHERE transaction_type NOT IN ('credit', 'transfer') GROUP BY category ORDER BY avg_amount DESC LIMIT 5;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1792,
    rows: [{"name": "checking", "avg": 1247.5}, {"name": "savings", "avg": 1679.6}, {"name": "credit", "avg": 2111.7}, {"name": "investment", "avg": 2543.8}],
  },
  {
    id: "demo-18",
    schema: "healthcare",
    complexity: "simple",
    question: "What is the most common appointment type?",
    generatedSql: `SELECT appointment_type, COUNT(*) AS count FROM healthcare.appointments GROUP BY appointment_type ORDER BY count DESC LIMIT 1;`,
    referenceSql: `SELECT appointment_type, COUNT(*) AS count FROM healthcare.appointments GROUP BY appointment_type ORDER BY count DESC LIMIT 1;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1929,
    rows: [{"name": "cardiology", "count": 14}, {"name": "neurology", "count": 21}, {"name": "pediatrics", "count": 28}, {"name": "general", "count": 35}],
  },
  {
    id: "demo-19",
    schema: "ecommerce",
    complexity: "simple",
    question: "List the products with a price greater than $50 and stock less than or equal to 5.",
    generatedSql: `SELECT * FROM products WHERE price > 50 AND stock <= 5;`,
    referenceSql: `SELECT * FROM products WHERE price > 50 AND stock <= 5;`,
    bleu: 1.0,
    execMatch: true,
    latencyMs: 1266,
    rows: [{"id": 1, "user_id": 100, "total": 125, "status": "pending"}, {"id": 2, "user_id": 101, "total": 250, "status": "shipped"}, {"id": 3, "user_id": 102, "total": 375, "status": "delivered"}, {"id": 4, "user_id": 103, "total": 500, "status": "pending"}],
  },
  {
    id: "demo-20",
    schema: "ecommerce",
    complexity: "highly_complex",
    question: "Find the average order value for each tier of users, considering only orders with a 'delivered' status, and include the tier name",
    generatedSql: `SELECT u.tier, AVG(o.total) AS avg_order_value FROM users u JOIN orders o ON u.id = o.user_id WHERE o.status = 'delivered' GROUP BY u.tier;`,
    referenceSql: `SELECT u.tier, AVG(o.total) AS avg_order_value FROM orders o JOIN users u ON o.user_id = u.id WHERE o.status = 'delivered' GROUP BY u.tier;`,
    bleu: 0.7381,
    execMatch: true,
    latencyMs: 1403,
    rows: [{"name": "electronics", "avg": 1247.5}, {"name": "clothing", "avg": 1679.6}, {"name": "books", "avg": 2111.7}, {"name": "home", "avg": 2543.8}],
  },
];

// Aggregated metrics from real eval runs (200-pair test set each)
export const EVAL_METRICS = {
  testSize: 200,
  finetuned: {
    overall: {
      executionAccuracy: 0.4600,
      validityRate:      0.9400,
      bleu:              0.5850,
    },
    bySchema: {
      "hr_system": { executionAccuracy: 0.4390, validityRate: 0.9268 },
      "ecommerce": { executionAccuracy: 0.3000, validityRate: 0.9500 },
      "fintech": { executionAccuracy: 0.5385, validityRate: 0.9744 },
      "healthcare": { executionAccuracy: 0.4500, validityRate: 0.9500 },
      "saas_analytics": { executionAccuracy: 0.5750, validityRate: 0.9000 }
    } as Record<SchemaName, BreakdownStat>,
    byComplexity: {
      "complex": { executionAccuracy: 0.3148, validityRate: 0.9074 },
      "moderate": { executionAccuracy: 0.4286, validityRate: 1.0000 },
      "highly_complex": { executionAccuracy: 0.2571, validityRate: 0.8000 },
      "simple": { executionAccuracy: 0.8780, validityRate: 1.0000 }
    } as Record<Complexity, BreakdownStat>,
  },
  baseline: {
    overall: {
      executionAccuracy: 0.0700,
      validityRate:      0.1500,
      bleu:              0.2036,
    },
    bySchema: {
      "hr_system": { executionAccuracy: 0.0732, validityRate: 0.1707 },
      "ecommerce": { executionAccuracy: 0.0750, validityRate: 0.3000 },
      "fintech": { executionAccuracy: 0.1538, validityRate: 0.2051 },
      "healthcare": { executionAccuracy: 0.0000, validityRate: 0.0250 },
      "saas_analytics": { executionAccuracy: 0.0500, validityRate: 0.0500 }
    } as Record<SchemaName, BreakdownStat>,
    byComplexity: {
      "complex": { executionAccuracy: 0.0185, validityRate: 0.1667 },
      "moderate": { executionAccuracy: 0.1000, validityRate: 0.1714 },
      "highly_complex": { executionAccuracy: 0.0571, validityRate: 0.1429 },
      "simple": { executionAccuracy: 0.0976, validityRate: 0.0976 }
    } as Record<Complexity, BreakdownStat>,
  },
} as const;
